name: Release

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  leveldb:
    name: Setup leveldb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update leveldb
        run: |
          git submodule init
          git submodule update --remote --merge
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git diff --exit-code || git commit -am "CI: Update leveldb-mcpe"
          git push

  release:
    name: Build application
    needs: leveldb
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
          check-latest: true

      - name: Setup google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_CONTENT }}' | base64 -d > app/google-services.json

      - name: Get keystore
        run: |
          echo "${{ secrets.NGUYENDUCK_KEYSTORE }}" > keystore.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch keystore.jks.asc > app/blocktopograph.jks

      - name: Build with Gradle
        run: ./gradlew -PsigningStorePassword="${{ secrets.SIGNING_STORE_PASSWORD }}" -PsigningKeyAlias="${{ secrets.SIGNING_KEY_ALIAS }}" -PsigningKeyPassword="${{ secrets.SIGNING_KEY_PASSWORD }}" assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: blocktopograph-release
          path: app/build/outputs/apk/release/app-release.apk